### ISSUE TITLE
ROS2 Jazzy + Ubuntu 24.04 Update

### ISSUE THREAD

**Issue by nishalangovender** [PepperlFuchs/pf_lidar_ros2_driver#12]
Will there be an update for ROS2 Jazzy integration?

**Comment by JnsHndr** [comment]
Please see the changes which came with PR https://github.com/PepperlFuchs/pf_lidar_ros2_driver/pull/13. These changes are still on the latest main branch and fix the build problems with Jazzy under Ubuntu 24.04. @nishalangovender please confirm if you can also build the driver.
Thank you and best regards
Jens

**Comment by nishalangovender** [comment]
Hi Jens. Yes, I can successfully build the driver. Thank you!
