### ISSUE TITLE
 Unable to communicate with device. Please check the IP address

### ISSUE THREAD

**Issue by Raunakabhani** [PepperlFuchs/pf_lidar_ros2_driver#9]
[INFO] [launch]: All log files can be found below /home/raunak20/.ros/log/2024-07-30-17-17-18-949331-raunak20-4983
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [ros_main-1]: process started with pid [4986]
[INFO] [robot_state_publisher-2]: process started with pid [4988]
[INFO] [rviz2-3]: process started with pid [4990]
[ros_main-1] [INFO] [1722340039.183981222] [pf_r2000]: device name: R2000
[ros_main-1] [INFO] [1722340039.184049092] [pf_r2000]: transport_str: udp
[ros_main-1] [INFO] [1722340039.184066850] [pf_r2000]: scanner_ip: 192.168.0.18
[ros_main-1] [INFO] [1722340039.184082837] [pf_r2000]: port: 80
[ros_main-1] [INFO] [1722340039.184098168] [pf_r2000]: start_angle: -1800000
[ros_main-1] [INFO] [1722340039.184114601] [pf_r2000]: max_num_points_scan: 0
[ros_main-1] [INFO] [1722340039.184156600] [pf_r2000]: watchdogtimeout: 60000
[ros_main-1] [INFO] [1722340039.184171991] [pf_r2000]: watchdog: 1
[ros_main-1] [INFO] [1722340039.184189529] [pf_r2000]: num_layers: 0
[ros_main-1] [INFO] [1722340039.184205236] [pf_r2000]: topic: /pf/scan
[ros_main-1] [INFO] [1722340039.184221495] [pf_r2000]: frame_id: scanner_link
[ros_main-1] [INFO] [1722340039.184236313] [pf_r2000]: packet_type: C
[ros_main-1] [INFO] [1722340039.184251750] [pf_r2000]: apply_correction: 0
[ros_main-1] [INFO] [1722340039.184350241] [pf_r2000]: start_angle: -1800000
[ros_main-1] HTTP ERROR: Failed to connect to 192.168.0.18 port 80: Connection refused
[ros_main-1] [ERROR] [1722340039.186184619] [pf_r2000]: Unable to communicate with device. Please check the IP address
[ros_main-1] [ERROR] [1722340039.186210342] [pf_r2000]: Unable to initialize device
[ros_main-1] terminate called without an active exception
[robot_state_publisher-2] Link scanner_link had 0 children

**Comment by JnsHndr** [comment]
Hello @Raunakabhani
Could you give please more information about this (see e.g. https://github.com/PepperlFuchs/pf_lidar_ros2_driver/issues/8 as a template)? For example, which ROS environment is used, what kind of R2000 device is used, which firmware and hardware version, etc. You could perhaps try to ping the device or if it is possible to establish a connection with PACTware, the R2000 DTM (https://www.pepperl-fuchs.com/usa/en/classid_53.htm?view=productdetails&prodid=86559#software) and device.
Best regards
Jens
